dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
install:
- pip install pydiatra pyflakes
script:
- ./maxproduct 15 test/forenames.txt test/surnames.txt
- python3 -m pydiatra .
- python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
