#!/usr/bin/python3

# Copyright © 2014 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse

from lib import maxproduct

def read_file(path):
    with open(path, 'rt', encoding='UTF-8') as file:
        return list(_read_file(file))

def _read_file(file):
    for line in file:
        try:
            n, text = line.split(None, 1)
        except ValueError:
            n, text = line, ''
        n = int(n)
        text = text.rstrip()
        yield n, text

def mul(x, y):
    [n1, s1] = x
    [n2, s2] = y
    return (n1 * n2, s1, s2)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('n', metavar='<n>', type=int)
    ap.add_argument('path1', metavar='<file1>')
    ap.add_argument('path2', metavar='<file2>')
    options = ap.parse_args()
    xs = read_file(options.path1)
    ys = read_file(options.path2)
    for n, x, y in maxproduct(xs, ys, n=options.n, fn=mul, reverse=True):
        print(n, x, y)

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
